# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Breaking Blue
email: akeenan2@nd.edu
description: > # this means to ignore newlines until "baseurl:"
  A 2-D multi-stage action adventure game in which you play as a 
  Blue involved in the struggle to overcome the Reds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://" # the base hostname & protocol for your site
github_username: KKA2

# Build settings
markdown: kramdown
